name: blazeplayer
description: "A professional video player application with social authentication."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # Firebase
  firebase_core: ^3.7.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  # Authentication Providers
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.2

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.6.2

  # Local Storage
  shared_preferences: ^2.3.3

  # UI Utilities
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.20.1
  logger: ^2.5.0
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  file_picker: ^8.0.0+1

  # Audio Player
  just_audio: ^0.9.40
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  audio_session: ^0.1.21
  palette_generator: ^0.3.3+4
  share_plus: ^12.0.1

  # In-app Browser
  webview_flutter: ^4.0.7
  webview_flutter_android: ^4.10.9
  image: ^4.5.4
  image_cropper: ^11.0.0
  crop_your_image: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
